package gol;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;

/**
 *
 * @author loux
 */
public class GameOfLifeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameOfLifeJFrame
     */
    public GameOfLifeJFrame() {
        geometry = new Geometry.Rectangle(200, 200);
        GameOfLife.randomInitialize(geometry);
        it_ = 0;
        gameOfLifeSwingWorker = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("This is the game of life");
        setPreferredSize(new java.awt.Dimension(800, 800));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(new GameOfLifeJPanel(), BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch (evt.getKeyChar()) {
            case 'p':
                if (gameOfLifeSwingWorker != null) {
                    gameOfLifeSwingWorker.cancel(true);
                }
                break;
            case 's':
                if (gameOfLifeSwingWorker == null || gameOfLifeSwingWorker.isCancelled()) {
                    gameOfLifeSwingWorker = new GameOfLifeSwingWorker(this);
                    java.awt.EventQueue.invokeLater(() -> {
                        gameOfLifeSwingWorker.execute();
                    });
                }
                break;
            case 'i':
                if (gameOfLifeSwingWorker != null) {
                    gameOfLifeSwingWorker.cancel(true);
                }
                GameOfLife.randomInitialize(geometry);
                jPanel1.repaint();
                break;
            case 'n':
                if (gameOfLifeSwingWorker != null) {
                    gameOfLifeSwingWorker.cancel(true);
                }
                String s = JOptionPane.showInputDialog(jPanel1, "Stupid, fucking white man,\n"
                        + "change the number of cells along the horizontal and vertical directions.",
                        "Format ex.: 100x100");
                String msg = "Problem while key pressed.";
                if (s != null && s.length() > 0) {
                    String[] split = s.split("x");
                    if (split.length == 2) {
                        try {
                            int nbColumns = Integer.parseInt(split[0]);
                            int nbRows = Integer.parseInt(split[1]);
                            geometry = new Geometry.Rectangle(nbRows, nbColumns);
                            GameOfLife.randomInitialize(geometry);
                            jPanel1.repaint();
                        } catch (NumberFormatException ex) {
                            msg += "Invalid input format for game of life size,\n"
                                    + "it should be the number of cells along the horizontal x the number of cells along vertical directions,\n"
                                    + "was given " + s + "\n";
                            msg += ex.getMessage();
                        }
                    } else {
                        msg += "Invalid input for game of life size, was given \"" + s + "\"";
                    }
                } else {
                    msg += "Null input size.";
                }
                if (msg.length() > 26) {
                    java.util.logging.Logger.getLogger(GameOfLifeJFrame.class.getName()).log(java.util.logging.Level.WARNING, msg);
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOfLifeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOfLifeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOfLifeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOfLifeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            GameOfLifeJFrame gameOfLifeJFrame = new GameOfLifeJFrame();
            gameOfLifeJFrame.setVisible(true);
        });
    }

    private final class GameOfLifeJPanel extends JPanel {

        public GameOfLifeJPanel() {
            addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    formMouseClicked(e);
                }

            });
        }

        private void formMouseClicked(MouseEvent e) {
            Cell cell = getCell(e.getPoint());
            cell.switchState();
            GameOfLifeJPanel.this.repaint();
        }

        public Cell getCell(java.awt.Point point) {
            Cell cell = null;
            int cellHeight = getCellHeight();
            int cellWidth = getCellWidth();
            double y = point.getY();
            double x = point.getX();
            int row = (int) y / cellHeight;
            int column = (int) x / cellWidth;
            cell = geometry.getCells()[0][row][column];
            return cell;
        }

        @Override
        public void paint(Graphics g) {
            super.paint(g);
            Graphics2D g2D = (Graphics2D) g;
            g2D.setPaint(Color.GRAY);
            int cellHeight = getCellHeight();
            int cellWidth = getCellWidth();
            for (int layer = 0; layer < geometry.getDepth(); layer++) {
                for (int row = 0; row < geometry.getHeight(); row++) {
                    int y = row * cellHeight;
                    for (int column = 0; column < geometry.getWidth(); column++) {
                        int x = column * cellWidth;
                        Cell cell = geometry.getCells()[layer][row][column];
                        if (cell.isAlive()) {
                            g2D.setPaint(Color.WHITE);
                        } else {
                            g2D.setPaint(Color.BLACK);
                        }
                        g2D.fillRect(x, y, cellWidth, cellHeight);
                    }
                }
            }
        }

        private int getCellHeight() {
            return ((int) Math.ceil((double) this.getHeight() / geometry.getHeight()));
        }

        private int getCellWidth() {
            return ((int) Math.ceil((double) this.getWidth() / geometry.getWidth()));
        }
    }

    private static class GameOfLifeSwingWorker extends SwingWorker<Integer, Geometry> {

        protected final GameOfLifeJFrame gameOfLifeJFrame;

        public GameOfLifeSwingWorker(GameOfLifeJFrame gameOfLifeJFrame) {
            this.gameOfLifeJFrame = gameOfLifeJFrame;
        }

        @Override
        protected void process(java.util.List<Geometry> chunks) {
            for (Geometry geometry : chunks) {
//                this.gameOfLifeJFrame.jPanel1.repaint();
            }
            this.gameOfLifeJFrame.jPanel1.repaint();
        }

        @Override
        protected void done() {
            try {
                if (!isCancelled()) {
                    System.out.println("stationary state reached in " + get() + " iterations.");
                }
            } catch (InterruptedException | ExecutionException ex) {
                Logger.getLogger(GameOfLifeJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        @Override
        protected Integer doInBackground() throws Exception {
            boolean isEvolving = true;
            while (!isCancelled() && isEvolving) {
                isEvolving = GameOfLife.nextGeneration(this.gameOfLifeJFrame.geometry, new Strategy.Default());
                publish(this.gameOfLifeJFrame.geometry);
                TimeUnit.MILLISECONDS.sleep(100);
                this.gameOfLifeJFrame.it_++;
            }
            return this.gameOfLifeJFrame.it_;
        }
    }

    private Geometry geometry;
    private int it_;
    private GameOfLifeSwingWorker gameOfLifeSwingWorker;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
